// Generated by CoffeeScript 1.6.3
(function() {
  _["default"] = function(object, key, default_) {
    if (_.has(object, key)) {
      return object[key];
    } else {
      return default_;
    }
  };

  _.float = function(number, default_) {
    number = parseFloat(number);
    if ((default_ != null) && _.isNaN(number)) {
      number = default_;
    }
    return number;
  };

  _.int = function(number, default_) {
    number = parseInt(number);
    if ((default_ != null) && _.isNaN(number)) {
      number = default_;
    }
    return number;
  };

  _.reversed = function(array) {
    array = array.slice(0);
    array.reverse();
    return array;
  };

  _.unflatten = function(array, length) {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = Math.ceil(array.length / length); 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push(array.slice(i * length, (i + 1) * length));
    }
    return _results;
  };

}).call(this);
