// Generated by CoffeeScript 1.6.2
(function() {
  _["default"] = function(object, key, default_) {
    if (_.has(object(key))) {
      return object[key];
    } else {
      return default_;
    }
  };

}).call(this);
